package app.softnetwork.notification.api

import app.softnetwork.persistence.jdbc.query.PostgresSchemaProvider

object NotificationPostgresLauncher extends NotificationApi with PostgresSchemaProvider
